import 'package:flutter/material.dart';

const List<String> entries = [
  "A big bug bit the little beetle, but the little beetle bit the big bug back.",
  "A fast ship sails on a calm sea.",
  "A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.",
  "A quick movement of the enemy will jeopardize six gunboats.",
  "A quivering Texas zombie fought republic linked jewelry.",
  "A very bad quack might jinx zippy fowls.",
  "A watched pot never boils.",
  "A wizard's job is to vex chumps quickly in fog.",
  "All that glitters is not gold.",
  "Amidst the mists and coldest frosts, with barest wrists and stoutest boasts, he thrusts his fists against the posts and still insists he sees the ghosts.",
  "Amidst the mists and coldest frosts,\nWith stoutest wrists and loudest boasts,\nHe thrusts his fists against the posts,\nAnd still insists he sees the ghosts.",
  "Bawds jog, flick quartz, vex nymphs.",
  "Better late than never.",
  "Betty bought a bit of butter, but the butter was bitter, so Betty bought a better butter to make the bitter butter better.",
  "Big July earthquakes confound zany experimental vow.",
  "Black bug bit a big black bear, but where is the big black bear that the black bug bit?",
  "Bored? Craving a pub quiz fix? Why, just come to the Royal Oak!",
  "Crisp crusts crackle and crunch.",
  "Curiosity killed the cat.",
  "Don't count your chickens before they hatch.",
  "Early to bed and early to rise, makes a man healthy, wealthy, and wise.",
  "Few black taxis drive up major roads on quiet hazy nights.",
  "Fickle jinx bog dwarves spy math quiz.",
  "Four quick steps, and I am at the white house gate.",
  "Fuzzy Wuzzy was a bear, Fuzzy Wuzzy had no hair, Fuzzy Wuzzy wasn't very fuzzy, was he?",
  "Give credit where credit is due.",
  "Glib jocks quiz nymph to vex dwarf.",
  "Hark! A vagrant haiku from the easel interrupts my mnemonic!",
  "He said he was not there yesterday; however, many people saw him there.",
  "Honesty is the best policy.",
  "How can a clam cram in a clean cream can?",
  "How much ground would a groundhog hog, if a groundhog could hog ground?",
  "How razorback jumping frogs can level six piqued gymnasts.",
  "How vexingly quick daft zebras jump, whilst all others go at a more leisurely pace.",
  "How vexingly quick daft zebras jump.",
  "I saw a kitten eating chicken in the kitchen.",
  "I saw Susie sitting in a shoeshine shop.",
  "I scream, you scream, we all scream for ice cream!",
  "I took the road less traveled,\nAnd that has made all the difference,\nI found my own way,\nAnd discovered my true essence.",
  "I'm not the pheasant plucker, I'm the pheasant plucker's mate, and I'm only plucking pheasants 'cause the pheasant plucker's late.",
  "If at first, you don't succeed, try, try again.",
  "If Peter Piper picked a peck of pickled peppers, where's the peck of pickled peppers Peter Piper picked?",
  "Irish wristwatch, Swiss wristwatch, Irish wristwatch, Swiss wristwatch.",
  "Jaded zombies acted quaintly but kept driving their oxen forward.",
  "My ex pub quiz crowd gave joyful thanks.",
  "My grandfather picks up quartz and valuable onyx jewels.",
  "Necessity is the mother of invention.",
  "One smart fellow, he felt smart. Two smart fellows, they felt smart. Three smart fellows, they all felt smart.",
  "Out of sight, out of mind.",
  "Pack my box with five dozen liquor jugs, and make sure they're all full!",
  "Pack my box with five dozen liquor jugs.",
  "Peter Piper picked a peck of pickled peppers, a peck of pickled peppers Peter Piper picked.",
  "Playing jazz vibe chords quickly excites my wife.",
  "Quick zephyrs blow, vexing daft Jim.",
  "Quickly jinxed wizards pluck ivy from the big quilt.",
  "Quirky spud boys can jam after waxing pious.",
  "Red lorry, yellow lorry, red lorry, yellow lorry, red lorry, yellow lorry.",
  "Rome wasn't built in a day.",
  "Rubber baby buggy bumpers bounce and break, but we still buy them anyway.",
  "She sells seashells by the seashore, and her sales are soaring.",
  "She stood in the storm,\nAnd when the wind did not blow her away,\nShe adjusted her sails,\nAnd continued on her way.",
  "She stood on the balcony, inexplicably mimicking him hiccoughing, and amicably welcoming him in.",
  "Six big juicy steaks sizzled in a pan as five workmen left the quarry.",
  "Sphinx of black quartz, judge my vow, for if you fail to do so,\nAll my life's but a sheer waste, as I vow to tell no one how I won this race.",
  "Sphinx of black quartz, judge my vow.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back!",
  "The cat in the hat sat on a mat, and looked quite content.",
  "The complex houses married and single soldiers and their families.",
  "The explorer was frozen in his big kayak just after making queer discoveries.",
  "The explorer was frozen in his big kayak just after making queer discoveries.",
  "The five boxing wizards jump quickly while the crowd cheered.",
  "The five boxing wizards jump quickly.",
  "The jay, pig, fox, zebra, and my wolves quack!",
  "The job requires extra pluck and zeal from every young wage earner.",
  "The July sun caused a fragment of black pine wax to ooze on the velvet quilt.",
  "The leaves rustle,\nIn the gentle breeze,\nThe sunlight dances,\nThrough the trees,\nAnd nature's beauty never ceases.",
  "The ocean waves crash,\nAgainst the shore,\nThe seagulls cry,\nI want to explore,\nThis world and more.",
  "The public was amazed to view the quickness and dexterity of the juggler.",
  "The Queen of Hearts she made some tarts,\nAll on a summer's day;\nThe Knave of Hearts he stole those tarts,\nAnd took them clean away.",
  "The quick brown fox jumps over a lazy dog in the new advertisement.",
  "The quick brown fox jumps over the lazy dog, and then takes a nap in the sun.",
  "The quick brown fox jumps over the lazy dog, but the dog barks and chases after him.",
  "The quick brown fox jumps over the lazy dog, but the dog doesn't care.",
  "The quick brown fox jumps over the lazy dog, who just yawns and goes back to sleep.",
  "The quick brown fox jumps over the lazy dog.",
  "The quick onyx goblin jumps over the lazy dwarf.",
  "The rain in Spain stays mainly in the plain, or so they say.",
  "The seething sea ceaseth and thus the seething sea sufficeth us.",
  "The sky is clear,\nNo clouds in sight,\nIt's a beautiful day,\nEverything is bright,\nAnd the world seems right.",
  "The sun beams,\nIn a summer's day,\nA warming light,\nA cheerful sway,\nAnd the world is never too hot to stay.",
  "The sun sets,\nOn the distant hills,\nA purple haze,\nThe world is still,\nAnd time seems to stand completely still.",
  "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
  "The water flows,\nDown the mountain stream,\nNature's symphony,\nA peaceful dream,\nAnd life is not as hard as it may seem.",
  "This land is given to the free,\nAnd all are equal, none by might\nShall e'er debased or cowered be.",
  "Three free throws. I saw a saw that could out saw any other saw I ever saw.",
  "Two driven jocks help fax my big quiz.",
  "Waxy and quivering, jocks fumble the pizza.",
  "We promptly judged antique ivory buckles for the next prize.",
  "We surely shall see the sun shine soon.",
  "When zombies arrive, quickly fax judge Pat.",
];

const List<String> difficultEntries = [
  "A penny saved is a penny earned, as the saying goes. Saving money and being mindful of our expenses can lead to greater financial stability and security.",
  "A penny saved is a penny earned, as the saying goes. While it may not seem like much at the time, saving small amounts of money can really add up over time. And who knows? You might just end up saving enough to buy something truly special.",
  "A picture is worth a thousand words, as the saying goes. Sometimes a visual representation can convey more information and emotion than words ever could.",
  "A rolling stone gathers no moss, but it does pick up plenty of interesting stories along the way. Whether it's traveling to new places, meeting new people, or trying new things, life is all about adventure.",
  "A watched pot never boils, as the saying goes. Sometimes it's best to be patient and let things unfold naturally.",
  "Absence makes the heart grow fonder, as the saying goes. Sometimes distance can actually strengthen our relationships and appreciation for the people we care about.",
  "Actions speak louder than words, as the saying goes. It's important to not only talk about our intentions and beliefs, but also to follow through with actions that align with those values.",
  "Actions speak louder than words, but sometimes words are all we have. When we can't find the right actions to take, we can always use our words to express our thoughts and feelings.",
  "All that glitters is not gold, but it sure is shiny! From sparkling diamonds to glittering gold, there's something undeniably alluring about shiny things.",
  "All work and no play makes Jack a dull boy, as the saying goes. It's important to find a balance between our responsibilities and leisure time.",
  "All's fair in love and war, as the saying goes. Sometimes we need to be strategic and use whatever means necessary to achieve our goals.",
  "An apple a day keeps the doctor away, as the old saying goes. While it may not be a foolproof method for staying healthy, eating a diet rich in fruits and vegetables is certainly a good start.",
  "Beauty is in the eye of the beholder, and it comes in many forms. From the breathtaking natural scenery to the intricate designs of a piece of artwork, beauty can be found all around us.",
  "Beauty is in the eye of the beholder, as the saying goes. What one person finds beautiful may not be the same as another person's perception.",
  "Better late than never, as the saying goes. While it's always best to be on time and punctual, sometimes things don't go as planned and we need to make the best of the situation.",
  "Don't put all your eggs in one basket, as the saying goes. Diversifying our investments and spreading out our risks can lead to greater stability and success.",
  "Every cloud has a silver lining, as the saying goes. Even in difficult or challenging situations, there can be opportunities for growth and positivity.",
  "Every cloud has a silver lining, even when it seems like everything is going wrong. Sometimes it's hard to see the good in a bad situation, but if we look hard enough, we can usually find something positive to hold onto.",
  "Good things come to those who wait, as the saying goes. Sometimes it's hard to be patient, but if we're willing to wait and work hard, good things will eventually come our way.",
  "Honesty is the best policy, as the saying goes. Being truthful and transparent in our interactions with others can build trust and respect.",
  "Honesty is the best policy, or so they say. While it may be tempting to tell a little white lie here and there, in the end, the truth always has a way of coming out.",
  "If at first you don't succeed, try, try again, as the saying goes. Persistence and perseverance are key to achieving our goals.",
  "If the shoe fits, wear it, as the saying goes. In other words, if something is a good fit for us and makes us happy, we should embrace it.",
  "Ignorance is bliss, as the saying goes. Sometimes it's easier to ignore the harsh realities of the world and focus on the positive aspects of life.",
  "It's not over until the fat lady sings, as the saying goes. In other words, don't give up until the very end, because anything can happen.",
  "It's the little things that count, as the saying goes. Small gestures and acts of kindness can make a big impact on someone's day.",
  "Knowledge is power, as the saying goes. The more we know, the better equipped we are to navigate the world and make informed decisions.",
  "Laughter is the best medicine, they say. Whether we're laughing at a funny joke, a silly meme, or a ridiculous pun, laughter has the power to lift our spirits and brighten our day.",
  "Let sleeping dogs lie, as the saying goes. In other words, it's sometimes best to avoid stirring up trouble or controversy.",
  "Money can't buy happiness, as the saying goes. While money can provide us with material comforts, true happiness comes from within and cannot be bought.",
  "Necessity is the mother of invention, as the saying goes. When faced with a problem or challenge, humans have a remarkable ability to come up with creative solutions.",
  "No man is an island, as the saying goes. We all need support, guidance, and friendship in order to thrive. Whether it's our family, our friends, or our community, we all need someone to lean on from time to time.",
  "Practice makes perfect, or so they say. While no one is truly perfect, we can all improve our skills and abilities through practice and dedication. Whether it's learning a new language or mastering a musical instrument, the key is to keep practicing and never give up.",
  "Rome wasn't built in a day, as the saying goes. Accomplishing great things takes time, patience, and persistence. But with hard work and dedication, anything is possible.",
  "The autumn leaves,\nFall to the ground,\nThe earth is painted,\nIn hues profound,\nAnd the beauty of the season knows no bound.",
  "The autumn leaves,\nIn a colorful display,\nA nature's art,\nA sight to sway,\nAnd the world is never too far to find a way.",
  "The best things in life are free, as the saying goes. Love, friendship, and experiences are often more valuable than material possessions.",
  "The bird sings,\nIn the morning light,\nA melodic tune,\nA joyful flight,\nAnd the world is never too dark to ignite.",
  "The birds fly,\nIn the open sky,\nA graceful sight,\nA soaring high,\nAnd the world is never too low to try.",
  "The birds sing,\nIn the early morn,\nThe world awakens,\nA new day is born,\nAnd the beauty of life is endlessly adorned.",
  "The butterfly flutters,\nIn the meadow's bloom,\nA delicate dance,\nA fairy's room,\nAnd the world is never too small to assume.",
  "The butterfly flutters,\nOn delicate wings,\nA dance of joy,\nA sight that sings,\nAnd the world is alive with all good things.",
  "The cactus blooms,\nIn the desert heat,\nA splash of color,\nA rare retreat,\nAnd the world is never too dry to be neat.",
  "The cherry blossoms,\nIn the springtime air,\nA sea of pink,\nA beauty rare,\nAnd the scent of the season fills the air.",
  "The cherry blossoms,\nIn the springtime breeze,\nA pink canvas,\nA nature's tease,\nAnd the world is never too cold to please.",
  "The city sleeps,\nIn the dead of night,\nThe neon lights,\nA colorful sight,\nAnd the skyline looks like an angel taking flight.",
  "The cricket chirps,\nIn the starry night,\nA lullaby of nature,\nA sound so right,\nAnd the world is at peace, without a single fight.",
  "The daisy blooms,\nIn a meadow green,\nA simple beauty,\nA natural sheen,\nAnd the world is never too complex to be seen.",
  "The devil is in the details, as the saying goes. Paying attention to the small details can often make a big difference in achieving our goals.",
  "The eagle soars,\nIn the mountain's crest,\nA regal flight,\nA nature's quest,\nAnd the world is never too small to invest.",
  "The early bird catches the worm, as the saying goes. Whether we're talking about getting up early to start our day or simply being proactive in our work, there's something to be said for taking initiative and getting ahead.",
  "The pen is mightier than the sword, as the saying goes. With a few well-chosen words, we can inspire, inform, persuade, and uplift. Words are truly powerful tools.",
  "The proof of the pudding is in the eating, as the saying goes. In other words, the true test of something is in how it performs in the real world. Whether we're talking about a product, a service, or a new idea, it's important to put it to the test and see how it holds up.",
  "The quick brown fox jumps over the lazy dog. But it's not just about speed and agility - the fox also has impressive hunting skills, using its keen senses and intelligence to catch prey.",
  "The rain pours,\nIn a steady beat,\nA cleansing force,\nA sound so sweet,\nAnd the world is alive with a rhythmic beat.",
  "The rainbow forms,\nIn the summer rain,\nA kaleidoscope,\nA color chain,\nAnd the world is never too plain to obtain.",
  "The rainbows form,\nIn the summer rain,\nA bridge of colors,\nA joyous gain,\nAnd the world is never too poor to maintain.",
  "The river bends,\nIn a winding stream,\nA flowing path,\nA watery dream,\nAnd the world is never too shallow to team.",
  "The river flows,\nIn a lazy stream,\nA peaceful journey,\nA gentle dream,\nAnd the world is never too fast to scheme.",
  "The river winds,\nThrough the countryside,\nA tranquil scene,\nWhere dreams reside,\nAnd peace and quiet is a welcome guide.",
  "The road to hell is paved with good intentions, as the saying goes. It's important to not only have good intentions, but also to follow through with actions that align with those intentions.",
  "The rose blooms,\nIn the garden's soil,\nA fragrant beauty,\nA lover's foil,\nAnd the world is never too bitter to spoil.",
  "The rose blossoms,\nIn the garden's bed,\nA fragrant beauty,\nA love's spread,\nAnd the world is never too rough to be led.",
  "The snow falls,\nIn a winter's spell,\nA blanket of white,\nA frozen swell,\nAnd the world is never too warm to tell.",
  "The snow falls,\nSilent and white,\nA winter wonderland,\nA magical sight,\nAnd the world seems to be bathed in pure light.",
  "The snowdrifts pile,\nIn a winter's glee,\nA playtime wonder,\nA childish spree,\nAnd the world is never too serious to be free.",
  "The snowflakes fall,\nIn a delicate dance,\nA winter's tale,\nA frozen trance,\nAnd the world is never too cold to take a chance.",
  "The squeaky wheel gets the grease, as the saying goes. Sometimes we need to speak up and advocate for ourselves in order to get what we need and deserve.",
  "The stars align,\nIn a cosmic play,\nA celestial dance,\nA milky way,\nAnd the world is never too big to display.",
  "The stars shine,\nIn the clear night sky,\nA cosmic array,\nA heavenly high,\nAnd the world is never too plain to apply.",
  "The stars shine,\nIn the midnight sky,\nA million diamonds,\nA heavenly high,\nAnd the universe seems to be perfectly nigh.",
  "The stars twinkle,\nIn the midnight blue,\nA celestial dance,\nA sight so true,\nAnd the world is never too old to renew.",
  "The sun rises,\nIn a new dawn,\nA day of hope,\nA chance to spawn,\nAnd the world is never too dark to be gone.",
  "The sun sets,\nIn a fiery blaze,\nA brilliant show,\nA sight to amaze,\nAnd the world is never too shy to raise.",
  "The sun shines,\nOn a summer day,\nA warming light,\nA cheerful play,\nAnd the world is never too hot to stay.",
  "The sunflower faces,\nTowards the sun's rays,\nA cheerful delight,\nA brightening blaze,\nAnd the world is never too dreary to amaze.",
  "The sunflowers sway,\nIn the golden sun,\nA joyful dance,\nA happy run,\nAnd the world is never too big to have fun.",
  "The thunder rolls,\nIn a fearsome roar,\nA show of power,\nA tempest's core,\nAnd the world is never too small to explore.",
  "The thunderstorm rages,\nIn a wild display,\nA nature's wrath,\nA forceful array,\nAnd the world is never too peaceful to sway.",
  "The waterfall cascades,\nIn a rocky scene,\nA nature's art,\nA liquid sheen,\nAnd the world is never too dry to be green.",
  "The waves crash,\nOn the rocky shore,\nA symphony of sound,\nForevermore,\nAnd the world is never too loud to ignore.",
  "The waves crash,\nOn the sandy shore,\nA rhythmic beat,\nA sea's rapport,\nAnd the world is never too tame to explore.",
  "The wind blows,\nIn a gusty gale,\nA nature's voice,\nA whistling tale,\nAnd the world is never too calm to unveil.",
  "The wind chimes,\nIn a summer breeze,\nA tinkling sound,\nA peaceful ease,\nAnd the world is never too loud to appease.",
  "The wind howls,\nIn a winter storm,\nA force of nature,\nA powerful form,\nAnd the world is never too harsh to transform.",
  "The wind whispers,\nThrough the trees,\nA secret message,\nOnly nature sees,\nAnd the world is wrapped in mystery and ease.",
  "The wolves howl,\nIn the moonlit night,\nA primal call,\nA haunting sight,\nAnd the wilderness is never out of sight.",
  "There's no place like home, as Dorothy famously declared in The Wizard of Oz. Home is where we feel safe, loved, and comfortable, surrounded by the people and things we cherish most.",
  "Time heals all wounds, as the saying goes. While it's difficult to cope with pain and loss, the passage of time can help us to heal and move forward.",
  "Time heals all wounds, or so they say. But sometimes the wounds are too deep, too painful, and too persistent to ever fully heal. In those cases, we must learn to live with our scars and use them as a reminder of our strength and resilience.",
  "Two heads are better than one, as the saying goes. Collaborating with others and sharing ideas can lead to better solutions and outcomes.",
  "Variety is the spice of life, as the saying goes. Trying new things, exploring new places, and meeting new people can all add excitement and adventure to our lives.",
  "What goes around comes around, as the saying goes. In other words, our actions have consequences and can come back to us in unexpected ways.",
  "When in Rome, do as the Romans do. This age-old adage reminds us to be respectful and adaptable when we find ourselves in unfamiliar situations. Whether we're traveling to a new country or simply meeting new people, it's important to approach each situation with an open mind.",
  "When life gives you lemons, make lemonade, as the old saying goes. In other words, when faced with a difficult situation, try to find the silver lining and make the best of it.",
  "When the going gets tough, the tough get going, as the saying goes. When faced with adversity, it's important to stay strong and persevere through the challenges.",
  "You can't have your cake and eat it too, as the saying goes. Sometimes we need to make choices and sacrifices in order to achieve our goals.",
  "You can't judge a book by its cover, as the saying goes. We should never make assumptions about someone based solely on their appearance or first impressions.",
  "You can't judge a book by its cover, but you can certainly judge a person by their actions. Integrity, honesty, and kindness are just a few of the qualities that make a person truly admirable.",
  "You can't make an omelette without breaking a few eggs, as the saying goes. Sometimes achieving our goals requires making difficult choices and sacrifices, but in the end, the payoff can be well worth it.",
];

const List<String> debugText = [
  "  a",
  ".....................................................................",
  "                                                                                                                                                                                                                                 ",
];

class Reaction {
  final String text;
  final double fontSize;
  final Color color;
  const Reaction(this.text, [this.fontSize = 32, this.color = Colors.black]);
}

const Map<int, Map<int, List<Reaction>>> reactions = {
  //wpm : { acc : [Reaction("reaction1"), Reaction("reaction2")]},
  0: {
    0: [
      Reaction("ಠ⁠_⁠ಠ", 128, Colors.red),
    ],
  },
  20: {
    0: [
      Reaction("Try to improve your accuracy."),
      Reaction("Practice makes perfect, keep going!"),
    ],
    75: [
      Reaction("Good effort, keep practicing for better speed and accuracy."),
      Reaction("You're doing fine...", 64, Colors.deepOrange)
    ],
    100: [
      Reaction(
          "You have excellent accuracy, keep working on increasing your speed!"),
      Reaction(
          "Your accuracy is impressive, keep practicing for faster speeds!"),
      Reaction("Great job on accuracy, now focus on increasing your speed!"),
    ],
  },
  40: {
    0: [
      Reaction("Focus on improving your accuracy for better results."),
      Reaction("You can do better, don't give up!"),
    ],
    75: [
      Reaction("Nice work, keep practicing for better speed and accuracy."),
      Reaction("You're doing well.", 64, Colors.orange)
    ],
    100: [
      Reaction("Impressive accuracy and good speed, keep practicing."),
      Reaction(
          "Great job on accuracy and speed, keep practicing for even faster speeds!"),
    ],
  },
  80: {
    0: [
      Reaction(
          "Your speed is impressive, keep working on increasing your accuracy."),
      Reaction("Great job on speed, keep practicing for even better accuracy!"),
    ],
    75: [
      Reaction("o7", 128),
      Reaction("You're very good!", 64, Color.fromARGB(255, 150, 161, 43)),
    ],
    100: [
      Reaction("You're a typing pro, keep up the good work!"),
      Reaction("🔥", 128),
    ],
  },
  120: {
    0: [
      Reaction("How are you this fast, yet so inaccurate? 🤣"),
      Reaction("Accuracy seems to be your only problem..."),
    ],
    75: [
      Reaction("You're so close to the top...!"),
      Reaction("This is amazing!", 64, Color.fromARGB(255, 154, 182, 52)),
    ],
    100: [
      Reaction("You're a typing legend, keep up the amazing work!"),
      Reaction("Incredible work on both speed and accuracy, well done!"),
      Reaction("⭐", 128, Colors.yellow),
    ],
  },
  160: {
    0: [
      Reaction(
          "You're too fast considering how many mistakes you're making 🧐"),
    ],
    75: [
      Reaction("This is almost perfect!", 64, Colors.green),
      Reaction("⚡", 128, Colors.yellow),
    ],
    100: [
      Reaction("You're a typing god, keep up the amazing work!"),
      Reaction("Unbelievable work on both speed and accuracy, well done!"),
      Reaction("👑", 192),
    ],
  },
  250: {
    0: [
      Reaction("How did your friggin bot make any mistakes? 🤣"),
    ],
    100: [
      Reaction("🧐", 128),
    ],
  },
};

const comboStart = 10;
const List<Color> comboColors = [
  Color.fromARGB(255, 76, 175, 79),
  Color.fromARGB(255, 0, 150, 135),
  Color.fromARGB(255, 25, 118, 210),
  Color.fromARGB(255, 95, 65, 180),
  Color.fromARGB(255, 155, 39, 176),
  Color.fromARGB(255, 170, 50, 160),
  Color.fromARGB(255, 190, 70, 130),
  Color.fromARGB(255, 233, 90, 80),
  Color.fromARGB(255, 251, 138, 0),
  Color.fromARGB(255, 231, 162, 30),
  Color.fromARGB(255, 175, 174, 44),
  Color.fromARGB(255, 140, 183, 60),
];
