const List<String> entries = [
  "The five boxing wizards jump quickly.",
  "How vexingly quick daft zebras jump.",
  "Sphinx of black quartz, judge my vow.",
  "Pack my box with five dozen liquor jugs.",
  "The jay, pig, fox, zebra and my wolves quack.",
  "Waltz, bad nymph, for quick jigs vex.",
  "Jackdaws love my big sphinx of quartz.",
  "Amazingly few discotheques provide jukeboxes.",
  "A quick brown fox jumps over the lazy dog's back.",
  "Jaded zombies acted quaintly but kept driving their oxen forward.",
  "The five boxing wizards jump quickly and groovy.",
  "Quick zephyrs blow, vexing daft Jim.",
  "Sphinx of black quartz, hear my vow.",
  "My ex pub quiz crowd gave joyful thanks.",
  "The quick onyx goblin jumps over the lazy dwarf.",
  "How razorback jumping frogs can level six piqued gymnasts.",
  "A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.",
  "A quivering Texas zombie fought republic linked jewelry.",
  "Sixty zippers were quickly picked from the woven jute bag.",
  "The July sun caused a fragment of black pine wax to ooze on the velvet quilt.",
];
